"""empty message

Revision ID: 013e8897f1e5
Revises: b7a080040a23
Create Date: 2021-02-01 11:26:22.631460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013e8897f1e5'
down_revision = 'b7a080040a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
